[package]
name = "ascent-py"
version = "0.1.0"
edition = "2021"

[lib]
name = "ascent_py"
crate-type = ["cdylib"]

[dependencies]
ascent = "*"
pyo3 = { version = "0.20", features = ["extension-module"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
